services:
  - type: web
    name: social_media_api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt; python manage.py collectstatic --no-input; python manage.py migrate
    startCommand: gunicorn social_media_api.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: social_media_api.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: social_media_db
          property: connectionString
  - type: pserv
    name: social_media_db
    plan: free
    ipAddress: true
    region: oregon
    postgreSQLVersion: "15"
